### PR TITLE
feat: Initial project implementation

### PR DESCRIPTION
**Pull request by thiagopena**

### CODE REVIEW

**Comment by diogobaeder** [comment]
Sorry for the long delay to review this, @thiagopena , my bad.

First of all, thank you so much for the effort to put up this PR! I see that you were very careful with the tests and organization of the code.

However it's in a different direction that I wanted to take when I thought about the project initially; What I'd like to have is a library that already contains all the core Kubernetes models in it, and not a library whose only purpose is to generate that code. If you take, for example, the `kubernetes` library, or `pulumi`, they both contain models ready to use (without Pydantic though), you don't need to run anything to generate them for those libraries. The idea is that whoever uses our library only has to install it and will be able to use the models right away.

So here's a few recommendations for what to do:
* We can get the OpenAPI specs for K8s from here for example: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/v3 - instead of having to run Kubernetes locally in order to have them available. With them I think we might be able to generate the models.
* Having the models generated, we should commit them to the library to have them available as part of the package, and not ignore them from version control.
* We could setup scheduled workflows in GHA to generate them automatically for us, to make sure we'll be able to automatically get API updates transformed into models (but we may want to set this up later, to reduce the burden of having a first released version).

What do you think?

**Comment by thiagopena** [comment]
No worries @diogobaeder .
You mean something more like this, correct? https://github.com/coherent-oss/kubedantic/pull/2

**Comment by diogobaeder** [comment]
> No worries @diogobaeder .
> You mean something more like this, correct? https://github.com/coherent-oss/kubedantic/pull/2

Exactly! Should we close this PR in favor of the second one then?

**Comment by thiagopena** [comment]
Closed in favor of: https://github.com/coherent-oss/kubedantic/pull/2

**Pull request closed without merging**
